title: oskar1233
email: ooskar1233@yahoo.com
description: >-
  oskar1233's personal website - blog & portfolio
baseurl: ""
url: "https://oskar1233.eu"
twitter_username: oskar1233
github_username:  oskar1233

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

